name: 'configure vcpkg'
description: 'vcpkg configuration'
inputs:
  PAT:
    description: 'personal access token for accessing private repos'
    required: true
runs:
  using: 'composite'
  steps:

    - name: 'setup environment'
      shell: 'bash'
      run: |
        echo "VCPKG_BINARY_SOURCES=clear;nuget,GitHub,readwrite" >> $GITHUB_ENV
        echo "VCPKG_NUGET_REPOSITORY=https://github.com/helynranta/vcpkg-registry.git" >> $GITHUB_ENV
        echo "VCPKG_KEEP_ENV_VARS=GITHUB_AUTHORIZATION_TOKEN;BLENDER_ROOT" >> $GITHUB_ENV
        echo "VCPKG_FEATURE_FLAGS=manifests,versions,registries" >> $GITHUB_ENV

    - uses: actions/checkout@v3
      name: pull vcpkg
      with:
        repository: 'microsoft/vcpkg'
        ref: '2024.05.24'
        path: 'vcpkg'

    - name: cache vcpkg downloads.
      uses: pat-s/always-upload-cache@v3.0.1
      with:
        path: |
          ${{ github.workspace }}/vcpkg/downloads
        key: ${{ matrix.os }}-vcpkg-downloads
    
    - uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.os == 'windows-latest' }}
      name: setup msvc command prompt

    - uses: lukka/get-cmake@latest
      name: get latest cmake version

    - uses: helynranta/git-credential-approve@v1
      name: setup credentials for private vcpkg registry
      with:
        personal-access-token: ${{ inputs.PAT }}
        path: 'helynranta/vcpkg-registry'

    - name: bootstrap vcpkg
      shell: pwsh
      run: |
        ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat -disableMetrics

    - name: 'setup nuget credentials'
      shell: 'bash'
      run: >
        ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
        sources add
        -source "https://nuget.pkg.github.com/helynranta/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "helynranta"
        -password "${{ inputs.PAT }}"

    - name: 'setup nuget apikey'
      shell: 'bash'
      run: >
        `./vcpkg/vcpkg fetch nuget | tail -n 1`
        setapikey "${{ inputs.PAT }}" -Source "https://nuget.pkg.github.com/helynranta/index.json"
